modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/CreeperHost/MineTogether/issues"
license = "GNU General Public License v3.0"

[[mods]]
    modId = "minetogether"
    version = "${version}"
    displayName = "MineTogether"
    authors = "covers1624, Gigabit101, Cloudhunter, CreeperHost!"
    description = ''''''

[[dependencies.minetogether]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "architectury"
    mandatory = true
    versionRange = "[6.2.46,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.minetogether]]
    modId = "polylib"
    mandatory = true
    versionRange = "[1900.0.2,)"
    ordering = "AFTER"
    side = "BOTH"
