modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/CreeperHost/MineTogether/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "minetogether"
version = "${version}"
displayName = "MineTogether"
authors = "Gigabit101, Cloudhunter, CreeperHost"
description = ''''''
#logoFile = ""

[[dependencies.minetogether]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minetogether]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2, 1.19]"
ordering = "NONE"
side = "BOTH"

[[dependencies.minetogether]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.minetogether]]
modId = "polylib"
mandatory = true
versionRange = "[1801.0.2,)"
ordering = "AFTER"
side = "BOTH"
