modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/CreeperHost/MineTogether/issues"
license = "GNU General Public License v3.0"

[[mods]]
    modId = "minetogether"
    version = "${version}"
    displayName = "MineTogether"
    authors = "covers1624, Gigabit101, Cloudhunter, CreeperHost!"
    description = ''''''

[[dependencies.minetogether]]
    modId = "forge"
    mandatory = true
    versionRange = "[48,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.2]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "architectury"
    mandatory = true
    versionRange = "[10.0.16,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.minetogether]]
    modId = "polylib"
    mandatory = true
    versionRange = "[2002.0.3,)"
    ordering = "AFTER"
    side = "BOTH"
