modLoader = "javafml"
loaderVersion = "[1.0,)"
issueTrackerURL = "https://github.com/CreeperHost/MineTogether/issues"
license = "GNU General Public License v3.0"

[[mods]]
    modId = "minetogether"
    version = "${version}"
    displayName = "MineTogether"
    authors = "covers1624, Gigabit101, Cloudhunter, CreeperHost!"
    description = ''''''

[[dependencies.minetogether]]
    modId = "neoforge"
    type="required"
    versionRange = "[20.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "minecraft"
    type="required"
    versionRange = "[1.20.4]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.minetogether]]
    modId = "architectury"
    type="required"
    versionRange = "[11.0.9,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.minetogether]]
    modId = "polylib"
    type="required"
    versionRange = "[2004.0.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[mixins]]
config = "minetogether-neoforge.mixins.json"

[[mixins]]
config = "minetogether-common.mixins.json"
